### ISSUE TITLE
在Advance Query查询的时候是否支持Field Id呢？

### ISSUE THREAD

**Issue by DylanQiao** [vikadata/vika.java#15]
FieldName是可以修改的，但是FiledId不会变，有时候名字改了就查不到了，可以支持通过FieldId进行查询吗？

**Comment by shawndenggh** [comment]
高级查询有一个参数fieldKey，是指定返回字段的标识，默认是`name`，你可以指定fieldId为`id`,在sdk里可以使用`queryParam.withFieldKey(FieldKey.ID)`，那么结果都是以fieldId作为key返回，同时，查询时候使用`queryParam. withFields(Arrays.asList('fldXXXX'))`即可。
