### ISSUE TITLE
在公式中怎么过滤某个字段值不为空？

### ISSUE THREAD

**Issue by wangjiecpp** [vikadata/vika.java#21]
如题：在query的withFilter("{fieldName}!=null")
怎么在过滤条件中 指定某个字段的值不为空，即只查询有字段有值的记录行

**Comment by shawndenggh** [comment]
公式使用判断不为空可以使用 `{fieldName} != BLANK()`作为参数

**Comment by shawndenggh** [comment]
解决了吗？如果没问题的话，24小时后我将关闭问题咯

**Comment by shawndenggh** [comment]
resovle
